{% set name = "http3" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 911b1cab5886a7e0f44490283365e954a0e27e9de5f7f7d4c18e26983f5f18f3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi
    - chardet ==3.*
    - h11 ==0.8.*
    - h2 ==3.*
    - idna ==2.*
    - python >=3.6
    - rfc3986 ==1.*

test:
  imports:
    - http3
    - http3.dispatch

about:
  home: https://github.com/encode/http3
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.

extra:
  recipe-maintainers:
    - nicoddemus
