travis:
  secure:
    BINSTAR_TOKEN: Zs1POVZMv4jXvk6ikOmiEobVYNp3d+petSrWEqSjOkOnSK9AXFK2TNuSM6O3Gf5k5/wK3v8W4vbrANrTRgcYS/jcaqSFkHQp49txQSA707UFxw5fsIvidmP7NMudheopQR2jnYPoaOQ9hZCOoYcEH6CkhWb/+8JyR/s6ewPGUSKGNzPBc3HIRsSqeq9UjxVjHeaAO5oZuklxTKk7T8eeiU1Ey2H1b/WvImZRGiIKfVvOIoqr8W/zDsULiqKxFNIfu8Bis0BSN0CBjGArUFG8113pvGIpauejZIsh8raKqCgFFKbQiagXjJzn0X2bFuCfVRaWvnTQrEJcdML8C3GWRu5P2vv3yAjyM4QmjcMYQ39oa1XS4IlYAgFxc+/1/bv5W+STMdLVt7nf4yrlGhyolCd/kuXE/Zhh/xBYbpFsHwlOWeL3Uqm/rYUTY+Xb7rYLLfQY9m32UUi9R0PpoKB6nN58wf2XRMbfTYaercovfkkbUCkvLcK5GJcR5eEoo2t4zM3RC8iVng8buVsVp/rxlq8gdCztXIrc+rYpL9pU7zJ7IOm1CZ4LRRUSuQ5FdiOffo/DSuHhCJ58pWPu8Tra/YvH2t0MFqkPg20PVS54ZmPUHbAuivCiQNIAs5FTALkQthjGs/4OEyF08K66tNdguDG6YEgosVZD1YkqDJ15l90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
